version: '{build}'
os: Visual Studio 2015
clone_depth: 1

configuration:
- Release

branches:
  only:
  - lua-5.1
  - lua-5.2
  - lua-5.3
  - luajit-2.0
  - luajit-2.1

environment:
  matrix:
  - VS_VERSION: 12
    VS_NAME: 2013
    VS_PLATFORM: win32
  - VS_VERSION: 12
    VS_NAME: 2013
    VS_PLATFORM: x64
  - VS_VERSION: 14
    VS_NAME: 2015
    VS_PLATFORM: win32
  - VS_VERSION: 14
    VS_NAME: 2015
    VS_PLATFORM: x64

install:
- choco install -y InnoSetup
- set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

before_build:
- cmake -H. -Bbuild -G"Visual Studio %VS_VERSION% %VS_NAME%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DWITH_LUA=%APPVEYOR_REPO_BRANCH% -DCMAKE_INSTALL_PREFIX=build/install

build_script:
- cmake --build build --config Release --target pack

artifacts:
  - path: lua*installer.exe

deploy:
  provider: GitHub
  description: Release %APPVEYOR_REPO_TAG_NAME%
  auth_token:
    secure: 9u2iMRO2KmnGYYLq9tqm0su2eY3h9FprKV8600vkNsFVCcM0ukfaZuu6SDGb95a6
  artifact: /lua.+installer\.exe/
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
