version: '{build}'
os: Visual Studio 2015
clone_depth: 1

configuration:
- Release

install:
- choco install -y InnoSetup
- set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

before_build:
- cmake -H. -Bvs2013-x64 -G"Visual Studio 12 2013 Win64"
- cmake -H. -Bvs2013-x86 -G"Visual Studio 12 2013"
- cmake -H. -Bvs2015-x64 -G"Visual Studio 14 2015 Win64"
- cmake -H. -Bvs2015-x86 -G"Visual Studio 14 2015"



build_script:
- cmake --build vs2013-x64 --config Release --target pack
- cmake --build vs2013-x86 --config Release --target pack
- cmake --build vs2015-x64 --config Release --target pack
- cmake --build vs2015-x86 --config Release --target pack

artifacts:
  - path: LuaInstaller-vs*.exe

deploy:
  provider: GitHub
  description: Draft Release
  auth_token:
    secure: 9u2iMRO2KmnGYYLq9tqm0su2eY3h9FprKV8600vkNsFVCcM0ukfaZuu6SDGb95a6
  artifact: /LuaInstaller.+\.exe/
  draft: true
  prerelease: true
