version: '{build}'
os: Visual Studio 2015
clone_depth: 1

configuration:
- Release

install:
- choco install -y InnoSetup

before_build:
- cmake -H. -Bvs2013-x64 -G"Visual Studio 12 2013 Win64"
- cmake -H. -Bvs2013-x86 -G"Visual Studio 12 2013"
- cmake -H. -Bvs2015-x64 -G"Visual Studio 14 2015 Win64"
- cmake -H. -Bvs2015-x86 -G"Visual Studio 14 2015"



build_script:
- cmake --build vs2013-x64 --config Release --target installer
- cmake --build vs2013-x86 --config Release --target installer
- cmake --build vs2015-x64 --config Release --target installer
- cmake --build vs2015-x86 --config Release --target installer

artifacts:
  - path: LuaVM-vs*.exe

deploy:
  provider: GitHub
  description: Release of v$(appveyor_build_version)
  auth_token:
    secure: 9u2iMRO2KmnGYYLq9tqm0su2eY3h9FprKV8600vkNsFVCcM0ukfaZuu6SDGb95a6
  artifact: /LuaVM.+\.exe/
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
