version: '{build}'
os: Visual Studio 2015

configuration:
- Release

environment:
  matrix:
  - VS_VERSION: 12 2013
    VS_PLATFORM: win32
  - VS_VERSION: 12 2013
    VS_PLATFORM: x64
  - VS_VERSION: 14 2015
    VS_PLATFORM: win32
  - VS_VERSION: 14 2015
    VS_PLATFORM: x64

install:
- choco install -y curl InnoSetup

before_build:
- cmake -H. -Bbuild -G"Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DCMAKE_INSTALL_PREFIX=build/install

build_script:
- cmake --build build --config Release --target install

after_build:
- iscc 

artifacts:
  - path: LuaInstaller-%VS_PLATFORM%.zip
    name: LuaInstaller

deploy:
  release: LuaInstaller-v$(appveyor_repo_tag)
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: LuaInstaller-%VS_PLATFORM%.zip
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
